import type { PrecacheEntry } from 'workbox-precaching'

import { downloadZip } from 'client-zip'
import { setCacheNameDetails } from 'workbox-core'
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'

import type { StorageAdapter } from './storage/storage-adapter'

import { createNfsaAdapter } from './storage/nfsa-adapter'

let cachedStorage: null | StorageAdapter = null

async function getCachedStorage(): Promise<StorageAdapter> {
  if (!cachedStorage) {
    cachedStorage = await createNfsaAdapter()
  }
  return cachedStorage
}

declare const __BUILD_TIME__: string

// Force a new cache name on every build to avoid collision with stale content
setCacheNameDetails({
  prefix: 'tinyimg',
  suffix: __BUILD_TIME__,
})

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: (PrecacheEntry | string)[]
}

// An in-memory map to store ZIP manifests sent from the main thread
interface ManifestItem {
  path: string
  payloadKey: string
}

const zipManifests = new Map<string, ManifestItem[]>()

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'PREPARE_ZIP_STREAM') {
    const { batchId, manifest } = event.data
    if (batchId && manifest) {
      zipManifests.set(batchId, manifest)

      // Send acknowledgment back to main thread
      event.ports[0]?.postMessage({ batchId, type: 'MANIFEST_READY' })

      // Auto-cleanup if the download is never triggered (e.g. 5 minutes)
      setTimeout(
        () => {
          zipManifests.delete(batchId)
        },
        5 * 60 * 1000,
      )
    }
  }
})

// Register our custom fetch handler BEFORE Serwist to intercept ZIP downloads
// Use capture phase to ensure we run before Serwist
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url)

  if (!url.pathname.startsWith('/_/download-zip/')) {
    return
  }

  // Prevent Serwist's fetch handler from running
  event.respondWith(
    (async () => {
      // Drain preload response
      if ('preloadResponse' in event && event.preloadResponse) {
        await event.preloadResponse
      }

      const parts = url.pathname.split('/')
      const batchId = parts[3] ?? ''
      const filename = parts.slice(4).join('/') || 'images.zip'

      const manifest = zipManifests.get(batchId)
      if (!manifest) {
        console.error(`[SW] Manifest not found for batchId: ${batchId}`)
        return new Response('Not Found', { status: 404 })
      }
      zipManifests.delete(batchId)

      try {
        const storage = await getCachedStorage()

        async function postSwDiagnostic(message: string): Promise<void> {
          if (!import.meta.env.DEV) return
          const clients = await self.clients.matchAll()
          for (const client of clients) {
            client.postMessage({ message, type: 'SW_DIAGNOSTIC' })
          }
        }

        await postSwDiagnostic(`Starting ZIP with ${manifest.length} files`)

        // Create async generator that yields files as they're retrieved
        async function* fileSource() {
          if (!manifest) {
            console.error('[SW] Manifest is undefined in fileSource')
            return
          }

          let filesYielded = 0

          for (const entry of manifest) {
            const fileData = await storage.getBackedFile(entry.payloadKey)

            if (fileData) {
              yield { input: fileData, name: entry.path }
              filesYielded++
              await postSwDiagnostic(`Added ${filesYielded}/${manifest.length} files`)
            } else {
              console.warn(`[SW] Missing file: ${entry.path}`)
            }
          }

          await postSwDiagnostic(`Complete - ${filesYielded} files zipped`)
        }

        const zipOutput = downloadZip(fileSource())

        return new Response(zipOutput.body, {
          headers: {
            'Content-Disposition': `attachment; filename="${filename}"`,
            'Content-Type': 'application/zip',
          },
        })
      } catch (error) {
        if (import.meta.env.DEV) {
          const clients = await self.clients.matchAll()
          const errMsg = error instanceof Error ? error.message : String(error)
          for (const client of clients) {
            client.postMessage({ message: `SW: ERROR - ${errMsg}`, type: 'SW_DIAGNOSTIC' })
          }
        }

        return new Response('Streaming Failed', { status: 500 })
      }
    })(),
  )
})

// Cleanup old caches from previous versions
cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

self.addEventListener('install', () => {
  self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      self.clients.claim(),
      // Manual cleanup of old caches just in case Workbox's helper missed something
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames
            .filter((name) => name.startsWith('tinyimg-') && !name.endsWith(__BUILD_TIME__))
            .map((name) => caches.delete(name)),
        )
      }),
    ]),
  )
})
